# config.py
# Configuração dos Nós (ID: (IP, PORTA))
# O ID deve ser um inteiro único. O maior ID será o Líder inicial/preferencial.

import os

NODES = {
    1: ('192.168.86.33', 5001), # Máquina 1
    2: ('192.168.86.28', 5002), # Máquina 2 (Simulando localhost com portas diferentes)
    3: ('192.168.86.120', 5003)  # Máquina 3
}

# Database Configuration with multiple fallback options
# Priority: 1. Environment variables, 2. config_db.py (auto-generated), 3. Default values

def get_db_config():
    """Get database configuration from environment or config_db.py"""
    
    # Try to import from config_db.py (generated by db_setup.py)
    try:
        from config_db import DB_CONFIG as db_config_auto
        print("[*] Using database configuration from config_db.py")
        return db_config_auto
    except ImportError:
        pass
    
    # Fallback to environment variables or defaults
    config = {
        'user': os.getenv('MYSQL_USER', 'root'),
        'password': os.getenv('MYSQL_PASSWORD', ''),
        'host': os.getenv('MYSQL_HOST', '127.0.0.1'),
        'database': os.getenv('MYSQL_DATABASE', 'dist_db')
    }
    
    # Add socket if specified
    socket_path = os.getenv('MYSQL_SOCKET', '/var/run/mysqld/mysqld.sock')
    if socket_path and os.path.exists(socket_path):
        config['unix_socket'] = socket_path
    
    # Remove empty password if not set
    if not config['password']:
        del config['password']
    
    print("[*] Using database configuration from environment/defaults")
    return config

DB_CONFIG = get_db_config()