#!/usr/bin/env python3
"""
Verify the distributed database system configuration
"""

import sys
import os

def check_python_packages():
    """Check if required Python packages are installed"""
    print("[*] Checking Python packages...")
    try:
        import mysql.connector
        print("  ✓ mysql-connector-python is installed")
        return True
    except ImportError:
        print("  ✗ mysql-connector-python NOT installed")
        print("    Install with: pip install mysql-connector-python")
        return False

def check_database_config():
    """Check if database configuration is available"""
    print("\n[*] Checking database configuration...")
    
    # Check for config_db.py (generated by db_setup.py)
    if os.path.exists('config_db.py'):
        print("  ✓ config_db.py found (auto-generated configuration)")
        try:
            from config_db import DB_CONFIG
            print(f"    User: {DB_CONFIG.get('user')}")
            print(f"    Database: {DB_CONFIG.get('database')}")
            return True
        except Exception as e:
            print(f"  ✗ Error reading config_db.py: {e}")
            return False
    else:
        print("  ⚠ config_db.py not found")
        print("    Run: python3 db_setup.py")
        
        # Check environment variables
        if os.getenv('MYSQL_USER'):
            print("  ✓ Environment variables found:")
            print(f"    MYSQL_USER: {os.getenv('MYSQL_USER')}")
            print(f"    MYSQL_DATABASE: {os.getenv('MYSQL_DATABASE', 'dist_db')}")
            return True
        else:
            print("  ⚠ No environment variables set")
            print("    Will use default configuration (root with no password)")
            return True

def test_database_connection():
    """Test actual database connection"""
    print("\n[*] Testing database connection...")
    
    try:
        import mysql.connector
        from config import DB_CONFIG
        
        conn = mysql.connector.connect(**DB_CONFIG)
        cursor = conn.cursor()
        
        # Test database exists
        cursor.execute("SHOW DATABASES LIKE 'dist_db'")
        if cursor.fetchone():
            print("  ✓ Database 'dist_db' exists")
        else:
            print("  ✗ Database 'dist_db' NOT found")
            print("    Run: python3 db_setup.py")
            return False
        
        # Test table exists
        cursor.execute("USE dist_db")
        cursor.execute("SHOW TABLES LIKE 'usuarios'")
        if cursor.fetchone():
            print("  ✓ Table 'usuarios' exists")
        else:
            print("  ✗ Table 'usuarios' NOT found")
            print("    Run: python3 db_setup.py")
            return False
        
        # Test permissions
        cursor.execute("SELECT COUNT(*) FROM usuarios")
        count = cursor.fetchone()[0]
        print(f"  ✓ Can read from usuarios table ({count} rows)")
        
        cursor.close()
        conn.close()
        return True
        
    except Exception as e:
        print(f"  ✗ Connection failed: {e}")
        print("    Run: python3 db_setup.py")
        return False

def check_node_config():
    """Check node configuration"""
    print("\n[*] Checking node configuration...")
    try:
        from config import NODES
        print(f"  ✓ {len(NODES)} nodes configured:")
        for node_id, (ip, port) in NODES.items():
            print(f"    Node {node_id}: {ip}:{port}")
        return True
    except Exception as e:
        print(f"  ✗ Error reading node config: {e}")
        return False

def check_ports_available():
    """Check if ports are available"""
    print("\n[*] Checking port availability...")
    import socket
    from config import NODES
    
    all_available = True
    for node_id, (ip, port) in NODES.items():
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(1)
        result = sock.connect_ex((ip, port))
        sock.close()
        
        if result == 0:
            print(f"  ⚠ Node {node_id} port {port} is already in use")
            all_available = False
        else:
            print(f"  ✓ Node {node_id} port {port} is available")
    
    return all_available

def main():
    print("=" * 60)
    print("  Distributed Database System - Configuration Verification")
    print("=" * 60)
    print()
    
    checks = [
        ("Python Packages", check_python_packages),
        ("Database Config", check_database_config),
        ("Database Connection", test_database_connection),
        ("Node Configuration", check_node_config),
        ("Port Availability", check_ports_available),
    ]
    
    results = []
    for name, check_func in checks:
        try:
            result = check_func()
            results.append((name, result))
        except Exception as e:
            print(f"\n[!] Unexpected error in {name}: {e}")
            results.append((name, False))
    
    print("\n" + "=" * 60)
    print("  Summary")
    print("=" * 60)
    
    all_passed = True
    for name, result in results:
        status = "✓ PASS" if result else "✗ FAIL"
        print(f"  {status}: {name}")
        if not result:
            all_passed = False
    
    print()
    if all_passed:
        print("  🎉 All checks passed! System is ready.")
        print("\n  Next steps:")
        print("    1. Start nodes: python middleware.py <NODE_ID>")
        print("    2. Run client: python client.py")
    else:
        print("  ⚠ Some checks failed. Please fix the issues above.")
        print("\n  Quick fix:")
        print("    Run: python3 db_setup.py")
    print()

if __name__ == "__main__":
    main()
